// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzZ87bEwDZoLSXwOKGyZM_FF79o66EFP4',
    appId: '1:1098632884340:web:1680cdb35e250782ffe121',
    messagingSenderId: '1098632884340',
    projectId: 'whats-app-f8e4a',
    authDomain: 'whats-app-f8e4a.firebaseapp.com',
    storageBucket: 'whats-app-f8e4a.appspot.com',
    measurementId: 'G-H5V8TH3Q3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzbpd6RYfp-j9VG9noasBpTJ3Jns0xBmA',
    appId: '1:1098632884340:android:6196e4a968f51bfaffe121',
    messagingSenderId: '1098632884340',
    projectId: 'whats-app-f8e4a',
    storageBucket: 'whats-app-f8e4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHkcKVpTsh4CzkInIKK5wtHGmBiU8Foaw',
    appId: '1:1098632884340:ios:5697f47253baad44ffe121',
    messagingSenderId: '1098632884340',
    projectId: 'whats-app-f8e4a',
    storageBucket: 'whats-app-f8e4a.appspot.com',
    iosBundleId: 'com.example.ourWhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHkcKVpTsh4CzkInIKK5wtHGmBiU8Foaw',
    appId: '1:1098632884340:ios:b5e4cb428a6f78d4ffe121',
    messagingSenderId: '1098632884340',
    projectId: 'whats-app-f8e4a',
    storageBucket: 'whats-app-f8e4a.appspot.com',
    iosBundleId: 'com.example.whatsAppClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzZ87bEwDZoLSXwOKGyZM_FF79o66EFP4',
    appId: '1:1098632884340:web:854dcac7c6782e1fffe121',
    messagingSenderId: '1098632884340',
    projectId: 'whats-app-f8e4a',
    authDomain: 'whats-app-f8e4a.firebaseapp.com',
    storageBucket: 'whats-app-f8e4a.appspot.com',
    measurementId: 'G-RQ0TKHL5GM',
  );
}
